### ISSUE TITLE
tmk_core

### ISSUE THREAD

**Issue by fredizzimo** [tmk/infinity_ergodox#2]
Hi,

I noticed that the ininite_ergodox repository refers to the tmk_core repository as a subrepository. Is there a reason why it's setup this way, instead of using the core, or perhaps the flabbergast-tmk_chibios branch of the tmk_keyboard repository?

The reason why I'm asking is that the infinity_ergodox core version seems to lag behind the core of tmk_keyboard quite a bit. Also wouldn't it make sense to try to combine all these core versions into one, so it's easier to maintain? Or at least have only the chibios and the normal one?

**Comment by tmk** [comment]
Sorry for late reply.
I have plan to remove `core` branch of `tmk_keyboard` repo, instead I setup tmk_core repo for the same purpose. And 'flabbergast-tmk_chibios' branch was going to use as my temporary working place. Sorry for this confusion.

I'm going to develop mainly under tmk_core directory(git-subtree'd) in master branch of `tmk_keyboard` and I'll update `tmk_core` repo occasionally. So you can think `tmk_core` repo as more stable, hopefully :D

I'll integrate chibios into master of tmk_core soon later and update it more often. Then I'll also update tmk_core submodule in this repo.
